In [45]:
import numpy as np
import random
import time

def timer(func):
    """Декоратор для підрахунку часу виконання скрипту."""
    def wrapper(*args, **kwargs):
        start = time.perf_counter()
        res = func(*args, **kwargs)
        end = time.perf_counter()
        return res, end - start
    return wrapper

1. Виконати набір вправ. Всі завдання виконати 2 способами:
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та зробити висновки.

In [ ]:
#Вправа 2
@timer
def task_2_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    arr[::2, ::2] = 1
    arr[1::2, 1::2] = 1
    return arr

@timer
def task_2_iter(n):
    return [[1 if (i + j) % 2 == 0 else 0 for j in range(n)] for i in range(n)]

#Вправа 3
@timer
def task_3_numpy(n, m, r, c):
    arr = np.ones((n, m), dtype=int)
    arr[r, :] = 0
    arr[:, c] = 0
    return arr

@timer
def task_3_iter(n, m, r, c):
    return [[0 if i == r or j == c else 1 for j in range(m)] for i in range(n)]

#Вправа 5
@timer
def task_5_numpy(n):
    arr = np.zeros((n, n), dtype=int)
    arr[::2, :] = 1
    return arr

@timer
def task_5_iter(n):
    return [[1 if i % 2 == 0 else 0 for j in range(n)] for i in range(n)]

#Вправа 9
@timer
def task_9_numpy(n):
    return np.arange(n, -1, -1)

@timer
def task_9_iter(n):
    return [i for i in range(n, -1, -1)]

#Вправа 13 та 14
@timer
def task_13_iter():
    row1 = [0, 1] * 4
    row2 = [1, 0] * 4
    return [row1, row2] * 4

@timer
def task_14_numpy():
    return np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

#Вправа 16
@timer
def task_16_numpy(n):
    arr = np.arange(n + 1)
    arr[(arr > n / 4) & (arr < 3 * n / 4)] = 0
    return arr

@timer
def task_16_iter(n):
    return [0 if (n / 4 < i < 3 * n / 4) else i for i in range(n + 1)]

#Вправа 17
@timer
def task_17_numpy(n):
    arr = np.arange(n + 1)
    mask = (arr < n / 2) | (arr > 3 * n / 4)
    arr[mask] = arr[mask] * -1
    return arr

@timer
def task_17_iter(n):
    return [-i if (i < n / 2 or i > 3 * n / 4) else i for i in range(n + 1)]

#Вправа 20
@timer
def task_20_numpy(n):
    arr = np.random.rand(n)
    arr[np.argmax(arr)] = 0
    return arr

@timer
def task_20_iter(n):
    arr = [random.random() for _ in range(n)]
    if arr:
        max_idx = arr.index(max(arr))
        arr[max_idx] = 0
    return arr

def run_benchmarks():
    # Структура: (Назва, NumPy функція, Ітеративна функція, кортеж аргументів)
    tasks = [
        ("Вправа 2 (n=500)", task_2_numpy, task_2_iter, (500,)),
        ("Вправа 3 (n=500, m=500, r=10, c=10)", task_3_numpy, task_3_iter, (500, 500, 10, 10)),
        ("Вправа 5 (n=500)", task_5_numpy, task_5_iter, (500,)),
        ("Вправа 9 (n=10000)", task_9_numpy, task_9_iter, (10000,)),
        ("Вправа 13 та 14 (поле 8x8)", task_14_numpy, task_13_iter, ()), 
        ("Вправа 16 (n=10000)", task_16_numpy, task_16_iter, (10000,)),
        ("Вправа 17 (n=10000)", task_17_numpy, task_17_iter, (10000,)),
        ("Вправа 20 (n=10000)", task_20_numpy, task_20_iter, (10000,))
    ]

    # Виводимо перший рядок таблиці
    print(f"{'Завдання 1':<35} | {'NumPy (сек)':<15} | {'Ітеративно (сек)':<15} | {'Ефективність'}")
    print("-" * 85)

    for name, func_np, func_iter, args in tasks:
        # Символ * перед args "розпаковує" кортеж, передаючи аргументи у функцію
        _, time_np = func_np(*args)
        _, time_it = func_iter(*args)
        
        # Рахуємо, у скільки разів NumPy швидший (із захистом від ділення на 0)
        speedup = time_it / time_np if time_np > 0 else 0
        
        # Виводимо рядок з результатами
        print(f"{name:<35} | {time_np:<15.6f} | {time_it:<15.6f} | Швидше у {speedup:.1f} разів")

run_benchmarks()

Завданн 1                           | NumPy (сек)     | Ітеративно (сек) | Ефективність
-------------------------------------------------------------------------------------
Вправа 2 (n=500)                    | 0.000366        | 0.014097        | Швидше у 38.5 разів
Вправа 3 (n=500, m=500, r=10, c=10) | 0.000265        | 0.008283        | Швидше у 31.3 разів
Вправа 5 (n=500)                    | 0.000108        | 0.007835        | Швидше у 72.5 разів
Вправа 9 (n=10000)                  | 0.000022        | 0.000242        | Швидше у 11.0 разів
Вправа 13 та 14 (поле 8x8)          | 0.000029        | 0.000002        | Швидше у 0.1 разів
Вправа 16 (n=10000)                 | 0.000062        | 0.001281        | Швидше у 20.6 разів
Вправа 17 (n=10000)                 | 0.000075        | 0.001194        | Швидше у 16.0 разів
Вправа 20 (n=10000)                 | 0.000100        | 0.000333        | Швидше у 3.3 разів


2. Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().

In [12]:
#Матриця коефіцієнтів A та вектор вільних членів B для Варіанту 2
A = np.array([
    [1,  2,  3, -2],
    [1, -1, -2, -3],
    [3,  2, -1,  2],
    [2, -3,  2,  1]
])
B = np.array([6, 8, 4, -8])

#1.Розв'язок за формулами Крамера
def cramer_solve(matrix_a, vector_b):
    n = matrix_a.shape[0]
    #обчислює визначник матриці, що є основою методу Крамера.
    det_a = np.linalg.det(matrix_a)
    
    #якщо визначник матриці дорівнює нулю, система не має єдиного розв'язку/ перевіряємо, за доп функції
    if np.isclose(det_a, 0):
        raise ValueError("Визначник матриці дорівнює нулю. Метод Крамера не застосовується.")
        
    x = np.zeros(n)
    for i in range(n):
        #ств. копію матриці A та замінюємо i-тий стовпець на вектор B
        A_i = matrix_a.copy()
        A_i[:, i] = vector_b
        #зн. x_i за формулою Крамера (det_A_i / det_A)/ використовуємо стандартні функції лінійної алгебри
        x[i] = np.linalg.det(A_i) / det_a
    return x

#зн. корені
x_cramer = cramer_solve(A, B)

#2.Перевірки альтернативними методами
#матричним множенням перевіряємо, чи A * x_cramer дає вектор B
B_check = np.dot(A, x_cramer)

#оберненою матрицею: x = A^(-1) * B
x_inv = np.dot(np.linalg.inv(A), B)

#функцією numpy.linalg.solve()
x_solve = np.linalg.solve(A, B)

#3.Виведення результатів
print("Завдання 2: СЛАР\n")
print("Знайдені корені (Метод Крамера):")
for i, root in enumerate(x_cramer, 1):
    print(f"x{i} = {root:.4f}")

print("\nАвтоматичні перевірки: ")
#формуємо список тестів для numpy.allclose()
checks = [
    ("Перевірка a) Матричне множення (A * x_cramer == B)", np.allclose(B, B_check)),
    ("Перевірка b) Обернена матриця (x_inv == x_cramer)", np.allclose(x_cramer, x_inv)),
    ("Перевірка c) np.linalg.solve (x_solve == x_cramer)", np.allclose(x_cramer, x_solve))
]

#виводимо результати у вигляді таблиці
for name, is_passed in checks:
    status = "УСПІШНО" if is_passed else "ПОМИЛКА"
    print(f"{name:<55} | {status}")

Завдання 2: СЛАР

Знайдені корені (Метод Крамера):
x1 = 1.1250
x2 = 1.9375
x3 = -1.1250
x4 = -2.1875

Автоматичні перевірки: 
Перевірка a) Матричне множення (A * x_cramer == B)      | УСПІШНО
Перевірка b) Обернена матриця (x_inv == x_cramer)       | УСПІШНО
Перевірка c) np.linalg.solve (x_solve == x_cramer)      | УСПІШНО


3. Обчислити значення матричного виразу
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().


In [48]:
# Задаємо матриці A та B для Варіанту 2
A = np.array([
    [4,  5, -2],
    [3, -1,  0],
    [4,  2,  7]
])

B = np.array([
    [2,  1, -1],
    [0,  1,  3],
    [5,  7,  3]
])

# Списки для ітеративного методу
A_list = A.tolist()
B_list = B.tolist()

#з використанням універсальних функцій NumPy ---
@timer
def calc_numpy(matrix_a, matrix_b):
    return 3 * matrix_a - np.dot((matrix_a - 2 * matrix_b), matrix_b)

#за допомогою ітеративних конструкцій ---
def multiply_matrices(m1, m2):
    """Допоміжна функція для множення матриць звичайними циклами."""
    rows = len(m1)
    cols = len(m2[0])
    inner_dim = len(m1[0])
    res = [[0] * cols for _ in range(rows)]
    for i in range(rows):
        for j in range(cols):
            for k in range(inner_dim):
                res[i][j] += m1[i][k] * m2[k][j]
    return res

@timer
def calc_iter(list_a, list_b):
    n = len(list_a)
    # 3A
    part1 = [[3 * list_a[i][j] for j in range(n)] for i in range(n)]
    # A - 2B
    part2 = [[list_a[i][j] - 2 * list_b[i][j] for j in range(n)] for i in range(n)]
    # (A - 2B) * B
    part3 = multiply_matrices(part2, list_b)
    # 3A - (A - 2B)B
    final = [[part1[i][j] - part3[i][j] for j in range(n)] for i in range(n)]
    return final

#перевірка
def run_task3_benchmark():
    # Структура: (Назва, функція NumPy, функція ітеративна, аргументи NumPy, аргументи ітеративні)
    tasks = [
        ("Вираз 3A - (A - 2B)B", calc_numpy, calc_iter, (A, B), (A_list, B_list))
    ]

    print("Завдання 3: Матричний вираз\n")
    print(f"{'Завдання':<25} | {'NumPy (сек)':<15} | {'Ітеративно (сек)':<15} | {'Ефективність'}")
    print("-" * 80)

    for name, func_np, func_iter, args_np, args_it in tasks:
        #запускаємо функції через декоратор timer
        res_np, time_np = func_np(*args_np)
        res_it, time_it = func_iter(*args_it)
        
        speedup = time_it / time_np if time_np > 0 else 0
        
        #виводимо порівняння часу
        print(f"{name:<25} | {time_np:<15.6f} | {time_it:<15.6f} | Швидше у {speedup:.1f} разів")
        
        # Виконуємо перевірку через np.allclose()
        is_passed = np.allclose(res_np, np.array(res_it))
        print(f"Перевірка збігу результатів (np.allclose): {'УСПІШНО' if is_passed else 'ПОМИЛКА'}")
        print("\nФінальна матриця-результат:")
        print(res_np)

# Запускаємо тест
run_task3_benchmark()

Завдання 3: Матричний вираз

Завдання                  | NumPy (сек)     | Ітеративно (сек) | Ефективність
--------------------------------------------------------------------------------
Вираз 3A - (A - 2B)B      | 0.000076        | 0.000017        | Швидше у 0.2 разів
Перевірка збігу результатів (np.allclose): УСПІШНО

Фінальна матриця-результат:
[[ 12  12 -15]
 [ 33  39  30]
 [ 19  17  48]]
